language: node_js
node_js:
  - "node"

script:
  - "npm run test"
  - "npm run build"

deploy:
  provider: surge
  project: ./public/
  domain: brunosantana.surge.sh
  skip_cleanup: true
  on:
    branch: master

